In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
df=pd.read_csv(r"D:\Dual degree\Deep learning\Churn_Modelling.csv")

In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
df['Surname']= LE1.fit_transform(df['Surname'])

In [10]:
df

RowNumber  CustomerId  Surname  CreditScore Geography  Gender  Age  \
0             1    15634602     1115          619    France  Female   42   
1             2    15647311     1177          608     Spain  Female   41   
2             3    15619304     2040          502    France  Female   42   
3             4    15701354      289          699    France  Female   39   
4             5    15737888     1822          850     Spain  Female   43   
...         ...         ...      ...          ...       ...     ...  ...   
9995       9996    15606229     1999          771    France    Male   39   
9996       9997    15569892     1336          516    France    Male   35   
9997       9998    15584532     1570          709    France  Female   36   
9998       9999    15682355     2345          772   Germany    Male   42   
9999      10000    15628319     2751          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
df.shape

(10000, 14)

In [13]:
df['Gender'].replace({'Female':0, 'Male':1}, inplace=True)

In [14]:
df.head()

RowNumber  CustomerId  Surname  CreditScore Geography  Gender  Age  Tenure  \
0          1    15634602     1115          619    France       0   42       2   
1          2    15647311     1177          608     Spain       0   41       1   
2          3    15619304     2040          502    France       0   42       8   
3          4    15701354      289          699    France       0   39       1   
4          5    15737888     1822          850     Spain       0   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

In [15]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [18]:
df['Geography'].replace({'France':0, 'Spain':1, 'Germany':2}, inplace=True)

In [17]:
df

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          1       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          1       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
9995       9996    15606229     1999          771          0       1   39   
9996       9997    15569892     1336          516          0       1   35   
9997       9998    15584532     1570          709          0       0   36   
9998       9999    15682355     2345          772          2       1   42   
9999      10000    15628319     2751          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

NameError: name 'X' is not defined

In [20]:
X=df.iloc[:,0:-1].values

In [21]:
X

array([[1.0000000e+00, 1.5634602e+07, 1.1150000e+03, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.0000000e+00, 1.5647311e+07, 1.1770000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [3.0000000e+00, 1.5619304e+07, 2.0400000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [9.9980000e+03, 1.5584532e+07, 1.5700000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [9.9990000e+03, 1.5682355e+07, 2.3450000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+04, 1.5628319e+07, 2.7510000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [22]:
y=df.iloc[:, -1].values

In [23]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2)

In [26]:
X_train

array([[7.6140000e+03, 1.5768449e+07, 2.2680000e+03, ..., 1.0000000e+00,
        1.0000000e+00, 1.8431288e+05],
       [7.7740000e+03, 1.5679818e+07, 2.9000000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 6.6753100e+04],
       [3.3870000e+03, 1.5582016e+07, 8.8700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 6.2402380e+04],
       ...,
       [8.8940000e+03, 1.5612670e+07, 2.3400000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.2950896e+05],
       [2.5230000e+03, 1.5758056e+07, 3.9200000e+02, ..., 0.0000000e+00,
        0.0000000e+00, 1.1168757e+05],
       [8.7640000e+03, 1.5665159e+07, 3.3400000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.8872908e+05]])

In [27]:
X_test

array([[1.7190000e+03, 1.5762745e+07, 1.6480000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 1.3365338e+05],
       [1.9030000e+03, 1.5622017e+07, 3.4300000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 9.8820090e+04],
       [4.8280000e+03, 1.5665053e+07, 1.9420000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 3.2936440e+04],
       ...,
       [7.9590000e+03, 1.5802483e+07, 1.0990000e+03, ..., 1.0000000e+00,
        1.0000000e+00, 8.8837110e+04],
       [4.1640000e+03, 1.5636396e+07, 1.3120000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 1.9302244e+05],
       [8.9940000e+03, 1.5809265e+07, 1.3620000e+03, ..., 1.0000000e+00,
        1.0000000e+00, 1.3328773e+05]])

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc=StandardScaler()

In [30]:
X_train=sc.fit_transform(X_train)

In [31]:
X_train

array([[ 0.91091146,  1.07506704,  0.9000785 , ...,  0.64337173,
         0.96125019,  1.4631394 ],
       [ 0.96635624, -0.15958966,  1.64950125, ..., -1.55431138,
         0.96125019, -0.58005514],
       [-0.5538703 , -1.52200117, -0.73750505, ...,  0.64337173,
        -1.04031189, -0.65567086],
       ...,
       [ 1.35446969, -1.09498166, -1.5118295 , ...,  0.64337173,
         0.96125019,  0.51064468],
       [-0.85327211,  0.9302894 , -1.32447382, ..., -1.55431138,
        -1.04031189,  0.20090808],
       [ 1.30942081, -0.36379398, -1.39324996, ...,  0.64337173,
         0.96125019,  1.53989316]])

In [32]:
X_test=sc.fit_transform(X_test)

In [33]:
X_test

array([[-1.15648247,  1.00880676,  0.16902419, ...,  0.65699256,
        -0.99302433,  0.58746172],
       [-1.09281335, -0.93224675, -1.35295453, ...,  0.65699256,
         1.00702467, -0.01950934],
       [-0.08068193, -0.33865358,  0.51190676, ..., -1.52208725,
         1.00702467, -1.16753381],
       ...,
       [ 1.00273123,  1.55691079, -0.47125651, ...,  0.65699256,
         1.00702467, -0.19346305],
       [-0.31044441, -0.733918  , -0.22284159, ..., -1.52208725,
         1.00702467,  1.62196928],
       [ 1.36087004,  1.65045454, -0.16452823, ...,  0.65699256,
         1.00702467,  0.58109026]])

In [34]:
ann=tf.keras.models.Sequential()

In [35]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [36]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [37]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [38]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [39]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [40]:
ann.fit(X_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7934 - loss: 0.5456
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7987 - loss: 0.4607
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7858 - loss: 0.4512
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7950 - loss: 0.4338
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7994 - loss: 0.4199
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8135 - loss: 0.4115
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8168 - loss: 0.4180
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8302 - loss: 0.3969
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8265 - loss: 0.4091
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3844
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8392 - loss: 0.3907
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [41]:
df

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          1       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          1       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
9995       9996    15606229     1999          771          0       1   39   
9996       9997    15569892     1336          516          0       1   35   
9997       9998    15584532     1570          709          0       0   36   
9998       9999    15682355     2345          772          2       1   42   
9999      10000    15628319     2751          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [42]:
print(ann.predict(sc.transform([[1,15634602, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1,50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
[[ True]]
